name: run-tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        os: [ ubuntu-latest ]
        php: [ 8.2, 8.3, 8.4 ]
        laravel: [ 12.* ]
        stability: [ prefer-lowest, prefer-stable ]

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Force clean environment
        run: |
          rm -rf vendor composer.lock
          composer clear-cache

      - name: Force Upgrade of xmlseclibs
        run: |
          composer remove robrichards/xmlseclibs
          composer require robrichards/xmlseclibs:^3.1 --no-update

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Debug Installed Packages
        run: |
          php -v
          composer show robrichards/xmlseclibs
          composer why robrichards/xmlseclibs

      - name: Execute tests
        run: cp phpunit.xml.dist phpunit.xml

      - name: Execute tests
        run: vendor/bin/pest
        env:
          POSTFINANCE_B2B_USERNAME: ${{ secrets.POSTFINANCE_B2B_USERNAME }}
          POSTFINANCE_B2B_PASSWORD: ${{ secrets.POSTFINANCE_B2B_PASSWORD }}
          POSTFINANCE_B2B_WSDL: ${{ secrets.POSTFINANCE_B2B_WSDL }}
          POSTFINANCE_B2B_TESTS_PAYER_ID: ${{ secrets.POSTFINANCE_B2B_TESTS_PAYER_ID }}
          POSTFINANCE_B2B_TESTS_BILLER_ID: ${{ secrets.POSTFINANCE_B2B_TESTS_BILLER_ID }}
          POSTFINANCE_B2B_TESTS_TRANSACTION_ID: ${{ secrets.POSTFINANCE_B2B_TESTS_TRANSACTION_ID }}

      - name: Store Log Artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: Store report artifacts
          path: ./vendor/orchestra/testbench-core/laravel/storage/logs